package bsep.SIEMcenter.rules

import bsep.SIEMcenter.model.Log;
import bsep.SIEMcenter.model.LogStorage;

global bsep.SIEMcenter.model.LogStorage logStorage;

rule "Login fail"
    when
    $l1 : Log(
        $machine: machine,
        $type: type,
        $os: os,
        pass == true
    )
    Number(intValue >= 15)
        from accumulate(
            $l2: Log (
                this != $l1,
                os == $os,
                type == $type,
                machine == $machine,
                message == "Unsuccessful login attempt",
                this meets[5s] $l1,
                pass == true
            ),
            count($l2))
	then
	    modify($l1){ pass = false };
		logStorage.addLog("Too many unsuccessful login attempts from " + $machine);
endrule "ss"
    when
    $l1 : Log(
        $machine: machine,
        $type: type,
        $os: os,
        pass == true
    )
    Number(intValue >= ss)
        from accumulate(
            $l2: Log (
                this != $l1,
                os == $os,
                type == $type,
                machine == $machine,
                message == "s",
                this meets[sss] $l1,
                pass == true
            ),
            count($l2))
	then
        modify($l1){ pass = false };

end


rule "dasdas"
    when
    $l1 : Log(
        $machine: machine,
        $type: type,
        $os: os,
        pass == true
    )
    Number(intValue >= dassa)
        from accumulate(
            $l2: Log (
                this != $l1,
                os == $os,
                type == $type,
                machine == $machine,
                message == "sdas",
                this meets[dsadsas] $l1,
                pass == true
            ),
            count($l2))
	then
        modify($l1){ pass = false };

end


